### ISSUE TITLE
Machine Learning Engineer

### ISSUE THREAD

**Issue by heroc0111** [QuodAI/jobs#2]
<p align="center">
  <img src="https://s3-ap-southeast-1.amazonaws.com/quod.ai/logo-sm.png?raw=true"/>
</p>
<p align="center">Singapore, Vietnam | Engineering & Applied Sciences</p>

# Machine Learning Engineer

Are you bored and unchallenged at your job?

Do you want to work on something exciting, challenging and impactful?

[Quod AI](http://quod.ai) is a young and exciting AI/NLP start-up with an unmatched team of engineers and scientists. We’re applying Deep Learning and NLP on source code  to empower software engineering teams to develop software products faster and better. We want to revolutionize the way software products are built and to accelerate innovation worldwide. We are funded and backed by SGInnovate and Entrepreneur First.

### Team

![Team](https://s3-ap-southeast-1.amazonaws.com/quod.ai/IMG_4751_xs.jpg "Team")

Our [CEO](https://www.linkedin.com/in/hroussel/) is a well recognized thought leader and speaker on AI and Software Engineering. He is an ex Silicon Valley CTO with 10+ years of experience in the US. He is also an advisor and mentor for organizations such as the IBM AI XPRIZE, PlatoHQ (YC’16), RMIT, AngelHack and more.
Our [Chief Scientist](https://www.linkedin.com/in/mikhfilippov/) is an is an award winning mathematical physicist. He is an expert at modeling complex systems (weather, neurobiological systems, real estate and more). His research background has led him to create AI & NLP models at prestigious institutions (UCL, NTU Complexity Institute & Polytechnique Paris) which were used by world renowned organizations (NASA & MAS).

### Key Responsibilities

* Work closely with our software architect and data scientist to develop and maintain our core product.
* Develop highly scalable code that leverages ML, natural language processing and rules based models that integrates into our data pipeline.
* Adapt and deploy ML/AI models  (Java or Python, Elasticsearch, Redis, Apache Beam).
* Evaluate and improve ML/AI models  (Python, Tensorflow, Jupyter notebook).
* Work on the implementation of new features, leaving things properly implemented, well documented and delivered on time.
* Always be on the lookout for opportunities to create and improve. From our development process, up to final user’s experiences.

### Knowledge, Skills and Abilities

* Solid skills with Java or Python. 
* Relevant experience with AWS or Google Cloud.
* Superior analytical, conceptual and problem-solving skills.
* The ability to learn and iterate quickly.
* An obsession with agile and lean principles (GitHub, Trello).
* Experience with NLP a plus.

### Education and Experience

* University degree in computer science or similar education.
* Minimum 2 years of experience with focus on backend development.
* Experience in a research environment a plus.
* Strong verbal and written communication skills in English.

### Apply now

* Full time position 
* Salary at market rate

**==> Click [here](http://bit.ly/quod-ai-apply) to apply <==**

**Comment by phongddo** [comment]
Hi @hroussel , @mikhfilippov , may I ask whether this position is still open? Look forward to hearing from you 😄

**Comment by heroc0111** [comment]
Hi @blavocado , it is still open. Please fill out the form: http://bit.ly/quod-ai-apply. Thanks.

**Comment by phongddo** [comment]
Thanks @hroussel for your reply. I filled out the form around 1 week ago, hope to hear from you soon 😄
